{% set name = "xhtml2pdf" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xhtml2pdf-{{ version }}.tar.gz
  sha256: 1b81630a10eba833ddeda16933fd6625471f16b93c352d954f552e5a608e7465

build:
  entry_points:
    - pisa = xhtml2pdf.pisa:command
    - xhtml2pdf = xhtml2pdf.pisa:command
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - arabic_reshaper >=3.0.0
    - html5lib >=1.0.1
    - pillow >=8.1.1
    - pyhanko >=0.12.1
    - pyhanko-certvalidator >=0.19.5
    - pypdf >=3.1.0
    - python-bidi >=0.4.2
    - reportlab >=3.5.53,<4
    - svglib >=1.2.1

test:
  imports:
    - xhtml2pdf
  commands:
    - pip check
    - pisa --help
    - xhtml2pdf --help
  requires:
    - pip

about:
  home: http://github.com/xhtml2pdf/xhtml2pdf
  summary: PDF generator using HTML and CSS
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mrakitin
