{% set name = "xhtml2pdf" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8e1db3d8acc9ff8071718b89b8967abb561a15d74d2cbd1606539c6d17660c4

build:
  number: 1
  entry_points:
    - pisa = xhtml2pdf.pisa:command
    - xhtml2pdf = xhtml2pdf.pisa:command
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - arabic_reshaper >=2.1.0
    - html5lib >=1.0.1
    - pillow >=8.1.1
    - pyhanko >=0.12.1
    - pyhanko-certvalidator >=0.19.5
    - pypdf3 >=1.0.5
    - python-bidi >=0.4.2
    - reportlab >=3.5.53
    - svglib >=1.2.1

test:
  imports:
    - xhtml2pdf
    - xhtml2pdf.builders
  commands:
    - pip check
    - pisa --help
    - xhtml2pdf --help
  requires:
    - pip

about:
  home: http://github.com/xhtml2pdf/xhtml2pdf
  summary: PDF generator using HTML and CSS
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mrakitin
